spring:
  datasource:
    url: jdbc:h2:file:./data/dev;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    defer-datasource-initialization: true # recreating the schema
    console:
      enabled: true
      path: /h2-console
      settings.trace: false #prevent trace output
      settings.web-allow-others: false #disable remote access
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect        
    hibernate:
      ddl-auto: create-drop #update      
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true  # only for TESTS!
        globally_quoted_identifiers: true
        order_inserts: true # batch all inserts of the same entity type and send it to DB in one go
        order_updates: true
        batch_versioned_data: true
        query:
          fail_on_pagination_over_collection_fetch: true #In case of propagation in memory throws exception
      jdbc:
        time_zone: UTC  
    show-sql: true  
  sql:
    init:
      #data-locations: data-trans.sql #initial data      
